name: 'Your name here'
description: 'Provide a description here'
author: 'Your name or organization here'
inputs:
  channel_id:
    required: false
    description: 'Add channel'
  thread_ts:
    required: false
    description: 'add thread id'
runs:
  using: 'node16'
  main: 'dist/index.js'
